### ISSUE TITLE
Conditionally show/hide contextMenuItem

### ISSUE THREAD

**Issue by Slavrix** [PerfectMemory/ngx-contextmenu#11]
Ive got a use case where the context menu is being used for "select".
If the item is already selected, im looking for a way to hide "select" and instead show "unselect".

I have passed the [contextMenuValue] in which contains my data related to the context menu.
In the angular inspector i can see that the templates inside the context-menu contain a value which looks to be passed in correctly.

```  
<context-menu #eventMenu>
    <ng-template contextMenuItem (execute)="releaseSingleShift($event.value.event)">
      Release
    </ng-template>
    <ng-template contextMenuItem (execute)="selectShift($event.value.event)">
      {{value.event.selected?'Unselect':'Select'}}
    </ng-template>
</context-menu>
```

This is what I have tried.

Is there a way to do this already and I just havn't found the documentation yet for it?

**Comment by Slavrix** [comment]
I found it, by going through the https://github.com/isaacplmann/ngx-contextmenu/issues/158
you need to add let-value to the ng-template and it works.

**Comment by sroucheray** [comment]
Hi @Slavrix, thanks for pointing this out. This should be added to the [documentation](https://perfectmemory.github.io/ngx-contextmenu/?path=/story/context-menu-documentation-in-a-nutshell--page) because its a pretty usual use case. If you think you can do a PR I would be glad (but do not feel like you have to). In the mean time I'll keep the issue open and mark it as documentation needed.

**Comment by Slavrix** [comment]
I'll give it a go to add it to the docs.

I also have tried passing the context menu to another component, so I can manage the menu's functions from a single component. The let-value doesn't work when I do this, but the menu does.

Any hints as to what I might be missing?

eg
parent.html
```
  <app-open-day-events-template
    [contextMenuTemplate]="eventMenu"
  >
  <!--This one opens the menu fine, but the value doesn't seem to bind properly, though I can see it in the angular inspector correctly-->
  </app-open-day-events-template>
  
  
  <app-event-week-template
    [weekEvent]="weekEvent"
    [contextMenu]="eventMenu"
    [contextMenuValue]="weekEvent"
  ><!--This one works fine-->
  </app-event-week-template>
  
  <context-menu #eventMenu>
    <ng-template contextMenuItem (execute)="openEventDetails($event.value.event)">
      Details
    </ng-template>
    <ng-template contextMenuItem (execute)="releaseSingleShift($event.value.event)">
      Release
    </ng-template>
    <ng-template contextMenuItem (execute)="selectShift($event.value.event)" let-value="value">
      {{value?.event?.selected?'Unselect':'Select'}}
    </ng-template>
  </context-menu>
```
app-open-day-events-template.html
```
      <div 
          [contextMenu]="contextMenuTemplate"
          [contextMenuValue]="event">
      </div>
```

**Comment by Slavrix** [comment]
I found that solution too.
https://github.com/isaacplmann/ngx-contextmenu#context-menu-in-a-different-component

probably also should be added to docs.

**Comment by sroucheray** [comment]
I added that to the documentation here https://perfectmemory.github.io/ngx-contextmenu/?path=/story/context-menu-documentation-in-a-nutshell--page

**Comment by ryanmattos** [comment]
Unfortunately it doesn't actually hide a contextMenuItem...

I have a list of items and possible options based on their status. Using `let-value` i can only hide its content (stuff inside `ng-template`), because the `value` will be available only to `ng-template` children, so the menu item is still there but empty...

**Comment by sroucheray** [comment]
@ryanmattos you should use the `[visible]` attribute of the `[contextMenuItem]` directive passing it a function, see https://perfectmemory.github.io/ngx-contextmenu/?path=/docs/context-menu-documentation-contextmenuitem--docs
