### ISSUE TITLE
@angular/cdk dependency ist still version 14

### ISSUE THREAD

**Issue by Timmeeeey** [PerfectMemory/ngx-contextmenu#13]
**Describe the bug**
@angular/cdk dependency ist still ^14.0.0. All other angular dependencies are ^15.0.0.

**Comment by sroucheray** [comment]
Hi @Timmeeeey, good catch I fixed it in 15.0.1
Thanks for your feedback

**Comment by Timmeeeey** [comment]
I just saw there are also angular peerDependencies in `projects/ngx-contextmenu/package.json` that are ^14.0.0

**Comment by sroucheray** [comment]
I will get there eventually :) A 15.0.2 is in the pipe.
