### ISSUE TITLE
Hiding a submenu

### ISSUE THREAD

**Issue by zantonz2** [PerfectMemory/ngx-contextmenu#14]
Thank you for your hard work and continued support.

There is one small question:
the version used is 14.1.0

After opening a submenu, when hovering the mouse cursor over an element without a submenu, the open one is not hidden. This behavior is even in the demo version.
It was expected that when hovering over an item without a submenu, the open one would disappear.

Tell me how this behavior can be corrected.

**Comment by sroucheray** [comment]
Hi @zantonz2,

Good catch. Thanks for submitting this issue. It seems to be a regression since the fork. I am going to give it a look.

**Comment by sroucheray** [comment]
@zantonz2 this should be fixed in 14.1.1 and 15.0.3. Can you check and close the issue if that's ok please ?

**Comment by zantonz2** [comment]
@sroucheray Yes thank you, in version 14.1.1 fixed the description of the behavior

**Comment by calldeludo** [comment]
hi guys im using version 8.0.0 and i'd need to fix it... any idea? is a big mess for my project to update angular core to 15...

**Comment by zantonz2** [comment]
@calldeludo
The old ngx-contextmenu project works well with 12-material.
I used 13-core and 12-material, then switched to core-14 and material-14.
Of course this is the wrong configuration, but it may help you.

**Comment by sroucheray** [comment]
@calldeludo I backported the fix to version 8.1.1. Hope this helps.
