### ISSUE TITLE
[help request] Dynamic submenus

### ISSUE THREAD

**Issue by baltzarmattsson** [PerfectMemory/ngx-contextmenu#27]
Hi, thanks for the continued development of the original repo.

I'm trying to achieve this:

![image](https://github.com/PerfectMemory/ngx-contextmenu/assets/20445589/1d9b9806-0cd4-4caf-941b-9a12956711f1)

but with dynamic items instead of a fixed template:

```
interface MenuItem {
    text: string;
    children?: MenuItem[];
}
```

```
const menuItems: MenuItem[] = [
    {
        text: "parent1",
        children: [
            {
                text: "inner1",
                children: [
                    { text: "inner2" }
                ]
            },
        ]
    },
    { text: "no children" }
]
```

Any idea how I can achieve this? Thanks

**Comment by sroucheray** [comment]
Hi @baltzarmattsson,

The documentation for submenus is here https://perfectmemory.github.io/ngx-contextmenu/?path=/docs/context-menu-documentation-in-a-nutshell--docs#sub-menu

It does not include an example with a second level of submenus but it should help you to achieve this.

**Comment by felipecarrillo100** [comment]
@baltzarmattsson I also need to do something like you described.  I managed to do it after a lot of experimentation and a few hacks.   

You can find a working example here:  https://github.com/felipecarrillo100/ng-custom-context-menu  
Feel free to try it and comment.
I basically created a unique context menu that is reused overall the components in the application.  The components interact with the component using a service that allows them to open menus with new options.  Have a look

**Comment by baltzarmattsson** [comment]
@felipecarrillo100 Amazing, thank you!

**Comment by sroucheray** [comment]
I am closing this issue considering by your last comment you found a solution. Please comment if this is not the case.
