### ISSUE TITLE
Question: Support for Angular 11?

### ISSUE THREAD

**Issue by chitgoks** [PerfectMemory/ngx-contextmenu#29]
The readme has the lowest level support for angular 12. Is there a support for Angular 11? Probably not included in the readme?

**Comment by sroucheray** [comment]
Hi @chitgoks !

Thanks for asking. 

Sure, this repo is originally forked from https://github.com/isaacplmann/ngx-contextmenu when the owner gave up updating with newer Angular version 12. So you can find a compatible version there with Angular version 11.
