### ISSUE TITLE
contextMenUtem - let-value not work

### ISSUE THREAD

**Issue by RGerhardt-Pressmind** [PerfectMemory/ngx-contextmenu#30]
I have the problem that let-value does not contain a value. It is an object, not a string, which in turn is supposed to have the value mobile filled, which it does not. value is apparently null.

What am I doing wrong or is this an error?

`
<context-menu #contactPersonContextMenu>
                            <ng-template contextMenuItem let-value (execute)="openEmail('tel:'+$event.value.mobile)" [visible]="visibleMobile">
                                Anrufen Mobil ({{value?.mobile}})
                            </ng-template>
</context-menu>
`

**Comment by sroucheray** [comment]
Hi @RGerhardt-Pressmind,

Did you set the `[contextMenuValue]` attribute's value on the `[contextMenu]` directive ?

![image](https://github.com/PerfectMemory/ngx-contextmenu/assets/169818/bb6ce7ad-d99e-4c91-b0b4-8383aea4fbea)


https://perfectmemory.github.io/ngx-contextmenu/?path=/docs/context-menu-documentation-in-a-nutshell--docs

**Comment by RGerhardt-Pressmind** [comment]
@sroucheray Yes, i have set
![Greenshot 2023-08-29 09 31 34](https://github.com/PerfectMemory/ngx-contextmenu/assets/69625642/68d317d5-d5c7-45c6-a93b-131c1437facc)

**Comment by sroucheray** [comment]
Hummm.... Sorry to ask, but could you provide a minimum reproduction of the problem on a [stackblitz](https://stackblitz.com/) please ?

**Comment by RGerhardt-Pressmind** [comment]
@sroucheray Here can you this reproduce:

https://stackblitz.com/edit/stackblitz-starters-ttbvtv?file=src%2Fmain.ts

{{value?.mobile}} is the value, but value is undefined

**Comment by sroucheray** [comment]
You spoted a bug. This should be fixed in 16.0.2 https://stackblitz.com/edit/stackblitz-starters-svke3h?file=src%2Fmain.ts

Can you check that it is good for you ?

**Comment by RGerhardt-Pressmind** [comment]
Yes, this is a perfect solution. Thank you very much 👍🏻
