### ISSUE TITLE
Cannot read properties of undefined (reading 'show')

### ISSUE THREAD

**Issue by mrjohnr** [PerfectMemory/ngx-contextmenu#32]
I've updated my app from Angular 16.2.5 to 17.0.5,ngx-contextmenu from 16.0.2 to  17.0.0
App is compiled successfully but no menu is shown,I got:

`core.mjs:11751 ERROR TypeError: Cannot read properties of undefined (reading 'show')
    at ContextMenuService.show (perfectmemory-ngx-contextmenu.mjs:906:21)
    at SchComponent.onContextMenu (sch.component.ts:977:29)
    at SchComponent_div_14_tr_29_ng_container_10_td_1_Template_td_click_0_listener (sch.component.html:340:6)
    at executeListenerWithErrorHandling (core.mjs:24586:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:24619:22)
    at HTMLTableCellElement.<anonymous> (platform-browser.mjs:681:17)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:14369:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:14369:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)`

I' using contextMenuService

```
...
@Input() contextMenu: ContextMenuComponent<any>;
...
constructor( private contextMenuService: ContextMenuService<any>) { }
...

 public onContextMenu($event: MouseEvent): void {
   ....
   this.contextMenuService.show(this.contextMenu, { x: $event.x, y: $event.y });
   $event.preventDefault();
   $event.stopPropagation();
 }
```
app.module:
```
import { ContextMenuModule, ContextMenuService } from '@perfectmemory/ngx-contextmenu';

 providers: [
    ContextMenuService
 ],
    imports: [
...
        ContextMenuModule
```

thanks

**Comment by sroucheray** [comment]
Hi @mrjohnr, could you provide a [stackblitz](https://stackblitz.com/) where you reproduce the problem please ? That would be super helpful.

**Comment by mrjohnr** [comment]
I've created a sample project and uploaded it here [https://pixeldrain.com/u/hQY7PYgm](https://pixeldrain.com/u/hQY7PYgm)

**Comment by sroucheray** [comment]
Sorry but I would really prefer and appreciate a https://stackblitz.com/, I cannot download and setup a local project for all open source issues I manage. It is too time-consuming. I hope you'll understand.

**Comment by mrjohnr** [comment]
tried Stackblitz but in a new Angular project there was no app.module so I give it up.
there is nothing new in test project,just calling  contextMenuService.show and got the error
is there any documentation/example for contextMenuService that I could follow? tried official docs but found nothing
rolled back my project to v16 and it works

**Comment by sroucheray** [comment]
@mrjohnr here is a working example https://stackblitz.com/edit/stackblitz-starters-gjkjgc?file=src%2Fmain.ts

**Comment by sroucheray** [comment]
And a slightly improved doc https://perfectmemory.github.io/ngx-contextmenu/?path=/docs/context-menu-documentation-contextmenuservice--docs

**Comment by mrjohnr** [comment]
great,found the issue:
I've added context menu variable template, previous worked without
`<context-menu #myContextMenu>`
then changed
 ` @Input() contextMenu: ContextMenuComponent<any>`
to
 ```
@ViewChild('myContextMenu')
 public contextMenu!: ContextMenuComponent<unknown>;
```

thanks
