### ISSUE TITLE
Unlimited submenus on click

### ISSUE THREAD

**Issue by quicknaps** [PerfectMemory/ngx-contextmenu#35]
**Describe the bug**
When clicking on a submenu a new sub menu opens every time overlaying the old sub menu.

This bug can be reproduced on the [demo](https://perfectmemory.github.io/ngx-contextmenu/?path=/story/context-menu-demo--demo) too.

On the demo, right click to open a context menu.
Then click on _Special pasties..._. 
Every single time _Special pasties_ is clicked a new sub menu is created.

**To Reproduce**
1. Go to the [demo](https://perfectmemory.github.io/ngx-contextmenu/?path=/story/context-menu-demo--demo).
2. Right click on _When you right click on this text, a context menu will appear_.
3. Click multiple times on _Special pasties..._.
4. Voila, multiple submenus have been created. You can check it in DevTools too.

**Expected behavior**
Old submenus will close when opening a new one.

**Stackblitz Example**
The [demo](https://perfectmemory.github.io/ngx-contextmenu/?path=/story/context-menu-demo--demo) is capable of reproducing the bug.

Here's a [video](https://ctrlv.tv/fryn)  of the issue.
[context-menu.webm](https://github.com/PerfectMemory/ngx-contextmenu/assets/31085293/74d2db32-5970-40b3-a95e-4fac06615152)

**Comment by sroucheray** [comment]
Good catch @quicknaps and thanks for the report ! Do you want to provide a fix ? I willing to accept PRs. If not I will try later on to fix the it.

**Comment by sroucheray** [comment]
Fixed in [17.0.2](https://github.com/PerfectMemory/ngx-contextmenu/commit/eaa0eea6b3612b80a75684b710215609abf64b2c)

**Comment by quicknaps** [comment]
Sorry for not replying earlier.
Thank you for the quick fix! :)
