### ISSUE TITLE
Multiple instances of context menu opened on one page

### ISSUE THREAD

**Issue by jandeu** [PerfectMemory/ngx-contextmenu#37]
**Describe the bug**

Hi, I'm not sure if this is an intended behaviour or a bug. When there is more then one instance of context menu on a page opening the second one does not close the first one. I'm pretty sure that in 15.1.1 only one context menu could be opened on a page.

**To Reproduce**
1. Add context menu to a component
2. Add two instances of the component on one page
3. Open context menu in each component
4. Two context menu are opened at the same time

**Expected behavior**

Only one context menu is opened at a page at the same time

**Stackblitz Example**

https://stackblitz.com/edit/stackblitz-starters-4fthiu

**Comment by sroucheray** [comment]
Hi @jandeu,

Thanks for the report.

It seems a bug. I need to look at this.

**Comment by andrewp24** [comment]
Also running into this. Do we know of an older version where this is not occurring?  Or if there happens to be a fix in the works. Thanks for your work on this @sroucheray !

**Comment by andrewp24** [comment]
Just went back and checked some previous versions. It works as expected back in version 16.0.2. The bump to 17.0.0 makes it so that the previous context menus even on separate components remain on the screen as @jandeu shows.

**Comment by sroucheray** [comment]
Hi @andrewp24,

Thanks for the check. I must admit I did not have time yet to look at this. I must plan some time.

**Comment by tomh-t** [comment]
Thanks! Just pulled 17.0.3 and can confirm this has resolved it 👍🏻

**Comment by sroucheray** [comment]
Hi @tomh-t, you were faster than me :) 

Solved in 17.0.3 https://stackblitz.com/edit/stackblitz-starters-kizdbv

**Comment by tomh-t** [comment]
> Hi @tomh-t, you were faster than me :)
> 
> Solved in 17.0.3 https://stackblitz.com/edit/stackblitz-starters-kizdbv

Just happened to hit this issue and saw you running the pipelines to release it 😉 🚤
