### ISSUE TITLE
menu seems to be opening off screen / below

### ISSUE THREAD

**Issue by peterainbow** [PerfectMemory/ngx-contextmenu#6]
now this could be my bug as i'm in the process of migrating an old project to ang 13
so lots of moving parts
when i call the show method on the contextmenuservice the menu seems to open off screen
can't tell for sure, but i am seeing the scroll bars suddenly appear, can't scroll down of course as if i try then the menu i assume closes
any pointers in how i can debug what is going on
i'll see if i can come up with a simpler project to reproduce
might not be new as i say long time since i've touched this project
[ currently unemployed and bored ]

btw thanks for doing this project, also

**Comment by sroucheray** [comment]
Hi @peterainbow,

I can think of missing CSS, you need to import both the CDK and the @perfectmemory/ngx-contextmenu stylesheets. Check the documentation here https://perfectmemory.github.io/ngx-contextmenu/?path=/story/context-menu-installation-and-setup--page

Other than that, one way to solve problems during a big migration is to try to reproduce a minimal setup of the problem using https://stackblitz.com for example. During this process either you'll see the mistake you did and you'll be able to fix it, you'll learn something, or if this is a library bug I'll have a minimal setup to debug. Its a win win.

BTW I hope your situation will improve and evolve as you wish. Life can be tough, be brave.

**Comment by sroucheray** [comment]
I am closing this issue.
